dist: bionic
language: java
jdk: oraclejdk11
script:
- cd src && python check_names.py && cd ..

cache:
  directories:
  - target/lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - cat target/pmd.xml
branches:
  only:
  - master

matrix:
  include:
    - name : mysql
      script:
        - sudo apt-get update && sudo apt-get install libssl-dev libmecab2 libjson-perl mecab-ipadic-utf8
        - sudo apt-get remove mysql-* && wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-server_8.0.20-1ubuntu18.04_amd64.deb-bundle.tar && tar -xvf mysql-server_8.0.20-1ubuntu18.04_amd64.deb-bundle.tar && yes | sudo dpkg -i *.deb
        - sudo mysql -e "CREATE USER 'sqlancer'@'localhost' IDENTIFIED BY 'sqlancer'; GRANT ALL PRIVILEGES ON * . * TO 'sqlancer'@'localhost';"
        - MYSQL_AVAILABLE=true mvn -Dtest=TestMySQL test
    - name: sqlite
      script:
        - mvn -Dtest=TestSQLite3 test
    - name: duckdb
      script: 
        - mvn -Dtest=TestDuckDB test
    - name: misc
      script:
        - mvn '-Dtest=!sqlancer.dbms.**' test
    - name: misc (java-8) 
        jdk:
        - openjdk8
      script:
        - mvn '-Dtest=!sqlancer.dbms.**' test
